# -*- coding: utf-8 -*-
"""cronjob_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WtTNOzHsLUZPhOGWhI0uxvSf6gA79QQ9
"""


#get data from covid19-public
import requests

base_url = "https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic"
res = requests.get(base_url + "/cases_malaysia.csv")
res2 = requests.get(base_url + "/cases_state.csv")
res3 = requests.get(base_url + "/case_age.csv")
#print(res.content)

#connect to postgreSQL
import psycopg2
conn = psycopg2.connect(database="postgres",
                        host="localhost",
                        user="postgres",
                        password=".",
                        port="5432")

print (conn)

#btye to str
content = str(res.content)
array_content = content.split("\\n")
# print(array_content)

# split data into array
for i in range(len(array_content)):
    array_content[i] = array_content[i].split(",")
    

array_content.pop(0) # remove collumn
array_content.pop() # remove last element
print(array_content)


# progmming py, sql, html, js, css
# 
# f^skELOR$D!Wgr7G#wFw 